services:
  - type: web
    name: laguna-dubai-system
    runtime: node
    repo: https://github.com/adhamkhaled1510/LagunaDubai-System
    plan: free
    region: frankfurt
    startCommand: node backend/server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /data/laguna.db
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
