-- Seed Data for Laguna Cafe
-- Run AFTER the schema SQL

-- Admin user
INSERT INTO users (id, username, password, name, role) VALUES ('u1', 'admin', 'admin123', 'أحمد علي', 'Administrator');

-- Employees (with PINs for login)
INSERT INTO employees (id, name, job, phone, salary, hireDate, status, pin) VALUES ('emp1', 'أحمد موظف', 'كافيه', '01011111111', '3000', '2026-01-01', 'active', '1234');
INSERT INTO employees (id, name, job, phone, salary, hireDate, status, pin) VALUES ('emp2', 'محمد موظف', 'شيف', '01022222222', '4000', '2026-01-01', 'active', '5678');

-- Cafe tables
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t1', 'طاولة 1', 2, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t2', 'طاولة 2', 2, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t3', 'طاولة 3', 2, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t4', 'طاولة 4', 2, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t5', 'طاولة 5', 4, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t6', 'طاولة 6', 4, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t7', 'طاولة 7', 4, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t8', 'طاولة 8', 4, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t9', 'طاولة 9', 6, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t10', 'طاولة 10', 6, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t11', 'طاولة 11', 6, 'available');
INSERT INTO cafe_tables (id, name, capacity, status) VALUES ('t12', 'طاولة 12', 6, 'available');

-- Customers
INSERT INTO customers (id, name, phone, totalSpent, visits, lastVisit) VALUES ('c1', 'أحمد محمد', '01012345678', 1200, 15, '2026-07-01');
INSERT INTO customers (id, name, phone, totalSpent, visits, lastVisit) VALUES ('c2', 'محمد علي', '01198765432', 850, 8, '2026-07-01');

-- Inventory
INSERT INTO inventory (id, name, category, quantity, unit, minQuantity) VALUES ('i1', 'قهوة تركية', 'قهوة', 50, 'كجم', 10);
INSERT INTO inventory (id, name, category, quantity, unit, minQuantity) VALUES ('i2', 'حليب', 'ألبان', 30, 'لتر', 5);
INSERT INTO inventory (id, name, category, quantity, unit, minQuantity) VALUES ('i3', 'سكر', 'مواد جافة', 100, 'كجم', 20);

-- Settings
INSERT INTO settings (key, value) VALUES ('cafeName', 'Laguna Cafe');
INSERT INTO settings (key, value) VALUES ('currency', 'ج.م');
INSERT INTO settings (key, value) VALUES ('taxRate', '14');
INSERT INTO settings (key, value) VALUES ('lowStockAlert', '5');

-- Products
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p1', 'سنجل تركي', 'Single Turkish Coffee', 'coffee', 30, 'images/menu/سنجل تركي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p2', 'دبل تركي', 'Double Turkish Coffee', 'coffee', 35, 'images/menu/دبل تركي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p3', 'فرنساوي', 'French Press', 'coffee', 45, 'images/menu/فرنساوي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p4', 'قهوة نكهات', 'Flavored Coffee', 'coffee', 45, 'images/menu/قهوة نكهات.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p5', 'نسكافية حليب', 'Nescafe with Milk', 'coffee', 50, 'images/menu/نسكافية حليب.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p6', 'سنجل اسبرسو', 'Single Espresso', 'coffee', 40, 'images/menu/سنجل اسبرسو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p7', 'دبل اسبرسو', 'Double Espresso', 'coffee', 55, 'images/menu/دبل اسبرسو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p8', 'ميكاتو', 'Mecato', 'coffee', 50, 'images/menu/ميكاتو.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p9', 'دبل ميكاتو', 'Double Mecato', 'coffee', 60, 'images/menu/دبل ميكاتو.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p10', 'امريكان كوفي', 'American Coffee', 'coffee', 50, 'images/menu/امريكان كوفي.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p11', 'لاتيه', 'Latte', 'coffee', 60, 'images/menu/لاتيه.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p12', 'كابتشينو', 'Cappuccino', 'coffee', 60, 'images/menu/كابتشينو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p13', 'كابتشينو فليفر', 'Flavored Cappuccino', 'coffee', 65, 'images/menu/كابتشينو فليفر.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p14', 'دارك موكا', 'Dark Mocha', 'coffee', 50, 'images/menu/دارك موكا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p15', 'وايت موكا', 'White Mocha', 'coffee', 59, 'images/menu/وايت موكا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p16', 'كورتادو', 'Cortado', 'coffee', 65, 'images/menu/كورتادو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p17', 'لاتيه فليفر', 'Flavored Latte', 'coffee', 65, 'images/menu/لاتيه فليفر.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p18', 'شاي احمر', 'Red Tea', 'hot', 20, 'images/menu/شاي احمر.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p19', 'شاي اخضر', 'Green Tea', 'hot', 25, 'images/menu/شاي اخضر.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p20', 'شاي فواكة', 'Fruit Tea', 'hot', 25, 'images/menu/شاي فواكة.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p21', 'شاي بلبن', 'Tea with Milk', 'hot', 50, 'images/menu/شاي بلبن.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p22', 'شاي كومبليت', 'Complete Tea', 'hot', 25, 'images/menu/شاي كومبليت.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p23', 'براد شاي', 'Tea Pot', 'hot', 60, 'images/menu/براد شاي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p24', 'اعشاب', 'Herbal Tea', 'hot', 25, 'images/menu/اعشاب.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p25', 'قرفة', 'Cinnamon', 'hot', 30, 'images/menu/قرفة.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p26', 'سحلب', 'Sahlab', 'hot', 50, 'images/menu/سحلب.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p27', 'جنزبيل', 'Ginger', 'hot', 30, 'images/menu/جنزبيل.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p28', 'هوت سيدر', 'Hot Cider', 'hot', 45, 'images/menu/هوت سيدر.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p29', 'هوت شوكلت', 'Hot Chocolate', 'hot', 50, 'images/menu/هوت شوكلت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p30', 'هوت كاراميل', 'Hot Caramel', 'hot', 55, 'images/menu/هوت كاراميل.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p31', 'هوت نوتيلا', 'Hot Nutella', 'hot', 55, 'images/menu/هوت نوتيلا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p32', 'هوت مارشملو', 'Hot Marshmallow', 'hot', 55, 'images/menu/هوت مارشملو.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p33', 'هوت اوريو', 'Hot Oreo', 'hot', 55, 'images/menu/هوت اوريو.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p34', 'آيس كوفي', 'Iced Coffee', 'ice', 65, 'images/menu/آيس كوفي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p35', 'آيس موكا', 'Iced Mocha', 'ice', 75, 'images/menu/آيس موكا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p36', 'آيس لاتيه', 'Iced Latte', 'ice', 65, 'images/menu/آيس لاتيه.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p37', 'آيس موكا وايت', 'Iced White Mocha', 'ice', 70, 'images/menu/آيس موكا وايت.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p38', 'اسبانش لاتيه', 'Spanish Latte', 'ice', 75, 'images/menu/اسبانش لاتيه.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p39', 'آيس لاتيه فليفر', 'Iced Flavored Latte', 'ice', 70, 'images/menu/آيس لاتيه فليفر.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p40', 'آيس ماتشا', 'Iced Matcha', 'matcha', 70, 'images/menu/آيس ماتشا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p41', 'ماتشا فرابيه', 'Matcha Frappe', 'matcha', 80, 'images/menu/ماتشا فرابيه.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p42', 'شوكلت', 'Chocolate Frappe', 'frappe', 60, 'images/menu/فرابيه شوكلت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p43', 'كارميل', 'Caramel Frappe', 'frappe', 65, 'images/menu/فرابيه كارميل.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p44', 'فانيليا', 'Vanilla Frappe', 'frappe', 65, 'images/menu/فرابيه فانيليا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p45', 'بندق', 'Hazelnut Frappe', 'frappe', 65, 'images/menu/فرابيه بندق.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p46', 'بيستاشيو', 'Pistachio Frappe', 'frappe', 70, 'images/menu/فرابيه بيستاشيو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p47', 'نوتيلا', 'Nutella Frappe', 'frappe', 65, 'images/menu/فرابيه نوتيلا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p48', 'تفاح اخضر', 'Green Apple Smoothie', 'smoothie', 50, 'images/menu/اسموزي تفاح اخضر.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p49', 'خوخ', 'Peach Smoothie', 'smoothie', 50, 'images/menu/اسموزي خوخ.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p50', 'اناناس', 'Pineapple Smoothie', 'smoothie', 50, 'images/menu/اسموزي اناناس.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p51', 'باشن فروت', 'Passion Fruit Smoothie', 'smoothie', 50, 'images/menu/اسموزي باشن فروت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p52', 'مانجو', 'Mango Smoothie', 'smoothie', 55, 'images/menu/اسموزي مانجو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p53', 'بطيخ', 'Watermelon Smoothie', 'smoothie', 55, 'images/menu/بطيخ.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p54', 'فراولة', 'Strawberry Smoothie', 'smoothie', 55, 'images/menu/فراولة.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p55', 'ميكس بيري', 'Mixed Berry Smoothie', 'smoothie', 55, 'images/menu/اسموزي ميكس بيري.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p56', 'كيوي', 'Kiwi Smoothie', 'smoothie', 60, 'images/menu/كيوي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p57', 'شوكلت', 'Chocolate Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك شوكلت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p58', 'كراميل', 'Caramel Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك كراميل.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p59', 'فانيليا', 'Vanilla Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك فانيليا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p60', 'فراولة', 'Strawberry Milkshake', 'milkshake', 65, 'images/menu/فراولة.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p61', 'خوخ', 'Peach Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك خوخ.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p62', 'مانجا', 'Mango Milkshake', 'milkshake', 65, 'images/menu/مانجا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p63', 'بندق', 'Hazelnut Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك بندق.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p64', 'بلو بيري', 'Blueberry Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك بلو بيري.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p65', 'مكس بيري', 'Mixed Berry Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك مكس بيري.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p66', 'نوتيلا', 'Nutella Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك نوتيلا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p67', 'وايت نوتيلا براوني', 'White Nutella Brownie Milkshake', 'milkshake', 70, 'images/menu/ميلك شيك وايت نوتيلا براوني.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p68', 'باشون فروت', 'Passion Fruit Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك باشون فروت.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p69', 'كلاسيك', 'Classic Yogurt', 'yogurt', 60, 'images/menu/زبادي كلاسيك.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p70', 'مانجو', 'Mango Yogurt', 'yogurt', 70, 'images/menu/زبادي مانجو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p71', 'فراوله', 'Strawberry Yogurt', 'yogurt', 70, 'images/menu/زبادي فراوله.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p72', 'خوخ', 'Peach Yogurt', 'yogurt', 70, 'images/menu/زبادي خوخ.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p73', 'موز', 'Banana Yogurt', 'yogurt', 70, 'images/menu/موز.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p74', 'بلو بيري', 'Blueberry Yogurt', 'yogurt', 70, 'images/menu/زبادي بلو بيري.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p75', 'باشن فروت', 'Passion Fruit Yogurt', 'yogurt', 70, 'images/menu/زبادي باشن فروت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p76', 'عسل', 'Honey Yogurt', 'yogurt', 65, 'images/menu/زبادي عسل.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p77', 'مكس فواكه', 'Mixed Fruit Yogurt', 'yogurt', 80, 'images/menu/زبادي مكس فواكه.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p78', 'ليمون', 'Lemon Juice', 'juice', 50, 'images/menu/ليمون.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p79', 'ليمون نعناع', 'Mint Lemon Juice', 'juice', 55, 'images/menu/ليمون نعناع.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p80', 'برتقال', 'Orange Juice', 'juice', 60, 'images/menu/برتقال.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p81', 'فراولة', 'Strawberry Juice', 'juice', 60, 'images/menu/فراولة.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p82', 'مانجا', 'Mango Juice', 'juice', 70, 'images/menu/مانجا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p83', 'جوافه', 'Guava Juice', 'juice', 70, 'images/menu/جوافه.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p84', 'موز', 'Banana Juice', 'juice', 70, 'images/menu/موز.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p85', 'بطيخ', 'Watermelon Juice', 'juice', 60, 'images/menu/بطيخ.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p86', 'بلح', 'Dates Juice', 'juice', 75, 'images/menu/بلح.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p87', 'افوكادو', 'Avocado Juice', 'juice', 80, 'images/menu/افوكادو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p88', 'ديلايت بانش', 'Delight Punch', 'cocktail', 65, 'images/menu/ديلايت بانش.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p89', 'تيمارا', 'Timara', 'cocktail', 65, 'images/menu/تيمارا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p90', 'فلوريدا', 'Florida', 'cocktail', 65, 'images/menu/فلوريدا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p91', 'دابومبا', 'Dabumba', 'cocktail', 70, 'images/menu/دابومبا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p92', 'وايت اوشن', 'White Ocean', 'cocktail', 70, 'images/menu/وايت اوشن.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p93', 'شهر زاد', 'Shahrzad', 'cocktail', 70, 'images/menu/شهر زاد.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p94', 'لاروز', 'La Rose', 'cocktail', 75, 'images/menu/لاروز.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p95', 'صن رايز', 'Sunrise Mojito', 'mojito', 50, 'images/menu/موهيتو صن رايز.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p96', 'صن شاين', 'Sunshine Mojito', 'mojito', 50, 'images/menu/موهيتو صن شاين.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p97', 'باشن فروت', 'Passion Fruit Mojito', 'mojito', 50, 'images/menu/موهيتو باشن فروت.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p98', 'توت', 'Berry Mojito', 'mojito', 50, 'images/menu/موهيتو توت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p99', 'شيري كولا', 'Cherry Cola Mojito', 'mojito', 50, 'images/menu/موهيتو شيري كولا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p100', 'شعير', 'Barley Mojito', 'mojito', 55, 'images/menu/موهيتو شعير.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p101', 'باور صودا', 'Power Soda Mojito', 'mojito', 75, 'images/menu/باور صودا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p102', 'بيبسي', 'Pepsi', 'cans', 30, 'images/menu/بيبسي.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p103', 'بيبسي دايت', 'Diet Pepsi', 'cans', 30, 'images/menu/بيبسي دايت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p104', 'اسبرايت', 'Sprite', 'cans', 30, 'images/menu/اسبرايت.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p105', 'ميرندا', 'Mirinda', 'cans', 30, 'images/menu/ميرندا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p106', 'فانتا', 'Fanta', 'cans', 30, 'images/menu/فانتا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p107', 'سفن اب', '7UP', 'cans', 30, 'images/menu/سفن اب.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p108', 'ماونتن ديو', 'Mountain Dew', 'cans', 30, 'images/menu/ماونتن ديو.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p109', 'تويست', 'Twist', 'cans', 30, 'images/menu/تويست.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p110', 'شويبس', 'Schweppes', 'cans', 30, 'images/menu/شويبس.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p111', 'فيروز', 'Fayrouz', 'cans', 35, 'images/menu/فيروز.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p112', 'في كولا', 'V Cola', 'cans', 35, 'images/menu/في كولا.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p113', 'فيوري', 'Fury', 'cans', 30, 'images/menu/فيوري.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p114', 'بيريل', 'Birell', 'cans', 35, 'images/menu/بيريل.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p115', 'ريد بول', 'Red Bull', 'cans', 75, 'images/menu/ريد بول.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p116', 'مونستر', 'Monster', 'cans', 75, 'images/menu/مونستر.webp', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p117', 'وافل دارك', 'Dark Waffle', 'dessert', 65, 'images/menu/وافل دارك.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p118', 'وافل نوتيلا', 'Nutella Waffle', 'dessert', 70, 'images/menu/وافل نوتيلا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p119', 'وافل وايت', 'White Waffle', 'dessert', 70, 'images/menu/وافل وايت.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p120', 'وافل لوتس', 'Lotus Waffle', 'dessert', 70, 'images/menu/وافل لوتس.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p121', 'وافل اوريو', 'Oreo Waffle', 'dessert', 75, 'images/menu/وافل اوريو.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p122', 'وافل ايس كريم & موز', 'Waffle Ice Cream & Banana', 'dessert', 80, 'images/menu/وافل ايس كريم & موز.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p123', 'مولتن كيك', 'Molten Cake', 'dessert', 65, 'images/menu/مولتن كيك.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p124', 'مولتن ايس كريم', 'Molten Ice Cream', 'dessert', 70, 'images/menu/مولتن ايس كريم.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p125', 'سينابون', 'Cinnabon', 'dessert', 55, 'images/menu/سينابون.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p126', 'سينابون نوتيلا', 'Nutella Cinnabon', 'dessert', 60, 'images/menu/سينابون نوتيلا.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p127', 'براونيز', 'Brownies', 'dessert', 50, 'images/menu/براونيز.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p128', 'فروت سالط', 'Fruit Salad', 'dessert', 60, 'images/menu/فروت سالط.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p129', 'فروت سالط ايس كريم', 'Fruit Salad Ice Cream', 'dessert', 70, 'images/menu/فروت سالط ايس كريم.png', 1);
INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES ('p130', 'فروت سالط ايس كريم مكسرات', 'Fruit Salad Ice Cream Nuts', 'dessert', 75, 'images/menu/فروت سالط ايس كريم مكسرات.png', 1);
