-- Supabase - فقط جدول المنتجات والبيانات
-- شغل دا في Supabase SQL Editor:
-- https://supabase.com/dashboard/project/szkmzvtsplinzrxxwpbu/sql/new

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  nameEn TEXT DEFAULT '',
  category TEXT NOT NULL,
  price REAL DEFAULT 0,
  image TEXT DEFAULT '',
  available INTEGER DEFAULT 1
);

ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;

INSERT INTO products (id, name, nameEn, category, price, image, available) VALUES
('p1', 'سنجل تركي', 'Single Turkish Coffee', 'coffee', 30, 'images/menu/سنجل تركي.webp', 1),
('p2', 'دبل تركي', 'Double Turkish Coffee', 'coffee', 35, 'images/menu/دبل تركي.webp', 1),
('p3', 'فرنساوي', 'French Press', 'coffee', 45, 'images/menu/فرنساوي.webp', 1),
('p4', 'قهوة نكهات', 'Flavored Coffee', 'coffee', 45, 'images/menu/قهوة نكهات.webp', 1),
('p5', 'نسكافية حليب', 'Nescafe with Milk', 'coffee', 50, 'images/menu/نسكافية حليب.png', 1),
('p6', 'سنجل اسبرسو', 'Single Espresso', 'coffee', 40, 'images/menu/سنجل اسبرسو.webp', 1),
('p7', 'دبل اسبرسو', 'Double Espresso', 'coffee', 55, 'images/menu/دبل اسبرسو.webp', 1),
('p8', 'ميكاتو', 'Mecato', 'coffee', 50, 'images/menu/ميكاتو.png', 1),
('p9', 'دبل ميكاتو', 'Double Mecato', 'coffee', 60, 'images/menu/دبل ميكاتو.png', 1),
('p10', 'امريكان كوفي', 'American Coffee', 'coffee', 50, 'images/menu/امريكان كوفي.png', 1),
('p11', 'لاتيه', 'Latte', 'coffee', 60, 'images/menu/لاتيه.webp', 1),
('p12', 'كابتشينو', 'Cappuccino', 'coffee', 60, 'images/menu/كابتشينو.webp', 1),
('p13', 'كابتشينو فليفر', 'Flavored Cappuccino', 'coffee', 65, 'images/menu/كابتشينو فليفر.png', 1),
('p14', 'دارك موكا', 'Dark Mocha', 'coffee', 50, 'images/menu/دارك موكا.webp', 1),
('p15', 'وايت موكا', 'White Mocha', 'coffee', 59, 'images/menu/وايت موكا.webp', 1),
('p16', 'كورتادو', 'Cortado', 'coffee', 65, 'images/menu/كورتادو.webp', 1),
('p17', 'لاتيه فليفر', 'Flavored Latte', 'coffee', 65, 'images/menu/لاتيه فليفر.png', 1),
('p18', 'شاي احمر', 'Red Tea', 'hot', 20, 'images/menu/شاي احمر.webp', 1),
('p19', 'شاي اخضر', 'Green Tea', 'hot', 25, 'images/menu/شاي اخضر.webp', 1),
('p20', 'شاي فواكة', 'Fruit Tea', 'hot', 25, 'images/menu/شاي فواكة.png', 1),
('p21', 'شاي بلبن', 'Tea with Milk', 'hot', 50, 'images/menu/شاي بلبن.webp', 1),
('p22', 'شاي كومبليت', 'Complete Tea', 'hot', 25, 'images/menu/شاي كومبليت.png', 1),
('p23', 'براد شاي', 'Tea Pot', 'hot', 60, 'images/menu/براد شاي.webp', 1),
('p24', 'اعشاب', 'Herbal Tea', 'hot', 25, 'images/menu/اعشاب.webp', 1),
('p25', 'قرفة', 'Cinnamon', 'hot', 30, 'images/menu/قرفة.webp', 1),
('p26', 'سحلب', 'Sahlab', 'hot', 50, 'images/menu/سحلب.webp', 1),
('p27', 'جنزبيل', 'Ginger', 'hot', 30, 'images/menu/جنزبيل.png', 1),
('p28', 'هوت سيدر', 'Hot Cider', 'hot', 45, 'images/menu/هوت سيدر.png', 1),
('p29', 'هوت شوكلت', 'Hot Chocolate', 'hot', 50, 'images/menu/هوت شوكلت.webp', 1),
('p30', 'هوت كاراميل', 'Hot Caramel', 'hot', 55, 'images/menu/هوت كاراميل.png', 1),
('p31', 'هوت نوتيلا', 'Hot Nutella', 'hot', 55, 'images/menu/هوت نوتيلا.png', 1),
('p32', 'هوت مارشملو', 'Hot Marshmallow', 'hot', 55, 'images/menu/هوت مارشملو.png', 1),
('p33', 'هوت اوريو', 'Hot Oreo', 'hot', 55, 'images/menu/هوت اوريو.png', 1),
('p34', 'آيس كوفي', 'Iced Coffee', 'ice', 65, 'images/menu/آيس كوفي.webp', 1),
('p35', 'آيس موكا', 'Iced Mocha', 'ice', 75, 'images/menu/آيس موكا.webp', 1),
('p36', 'آيس لاتيه', 'Iced Latte', 'ice', 65, 'images/menu/آيس لاتيه.webp', 1),
('p37', 'آيس موكا وايت', 'Iced White Mocha', 'ice', 70, 'images/menu/آيس موكا وايت.png', 1),
('p38', 'اسبانش لاتيه', 'Spanish Latte', 'ice', 75, 'images/menu/اسبانش لاتيه.webp', 1),
('p39', 'آيس لاتيه فليفر', 'Iced Flavored Latte', 'ice', 70, 'images/menu/آيس لاتيه فليفر.png', 1),
('p40', 'آيس ماتشا', 'Iced Matcha', 'matcha', 70, 'images/menu/آيس ماتشا.webp', 1),
('p41', 'ماتشا فرابيه', 'Matcha Frappe', 'matcha', 80, 'images/menu/ماتشا فرابيه.webp', 1),
('p42', 'شوكلت', 'Chocolate Frappe', 'frappe', 60, 'images/menu/فرابيه شوكلت.webp', 1),
('p43', 'كارميل', 'Caramel Frappe', 'frappe', 65, 'images/menu/فرابيه كارميل.webp', 1),
('p44', 'فانيليا', 'Vanilla Frappe', 'frappe', 65, 'images/menu/فرابيه فانيليا.webp', 1),
('p45', 'بندق', 'Hazelnut Frappe', 'frappe', 65, 'images/menu/فرابيه بندق.webp', 1),
('p46', 'بيستاشيو', 'Pistachio Frappe', 'frappe', 70, 'images/menu/فرابيه بيستاشيو.webp', 1),
('p47', 'نوتيلا', 'Nutella Frappe', 'frappe', 65, 'images/menu/فرابيه نوتيلا.webp', 1),
('p48', 'تفاح اخضر', 'Green Apple Smoothie', 'smoothie', 50, 'images/menu/اسموزي تفاح اخضر.png', 1),
('p49', 'خوخ', 'Peach Smoothie', 'smoothie', 50, 'images/menu/اسموزي خوخ.png', 1),
('p50', 'اناناس', 'Pineapple Smoothie', 'smoothie', 50, 'images/menu/اسموزي اناناس.png', 1),
('p51', 'باشن فروت', 'Passion Fruit Smoothie', 'smoothie', 50, 'images/menu/اسموزي باشن فروت.webp', 1),
('p52', 'مانجو', 'Mango Smoothie', 'smoothie', 55, 'images/menu/اسموزي مانجو.webp', 1),
('p53', 'بطيخ', 'Watermelon Smoothie', 'smoothie', 55, 'images/menu/بطيخ.webp', 1),
('p54', 'فراولة', 'Strawberry Smoothie', 'smoothie', 55, 'images/menu/فراولة.webp', 1),
('p55', 'ميكس بيري', 'Mixed Berry Smoothie', 'smoothie', 55, 'images/menu/اسموزي ميكس بيري.webp', 1),
('p56', 'كيوي', 'Kiwi Smoothie', 'smoothie', 60, 'images/menu/كيوي.webp', 1),
('p57', 'شوكلت', 'Chocolate Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك شوكلت.webp', 1),
('p58', 'كراميل', 'Caramel Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك كراميل.webp', 1),
('p59', 'فانيليا', 'Vanilla Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك فانيليا.webp', 1),
('p60', 'فراولة', 'Strawberry Milkshake', 'milkshake', 65, 'images/menu/فراولة.webp', 1),
('p61', 'خوخ', 'Peach Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك خوخ.webp', 1),
('p62', 'مانجا', 'Mango Milkshake', 'milkshake', 65, 'images/menu/مانجا.webp', 1),
('p63', 'بندق', 'Hazelnut Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك بندق.png', 1),
('p64', 'بلو بيري', 'Blueberry Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك بلو بيري.png', 1),
('p65', 'مكس بيري', 'Mixed Berry Milkshake', 'milkshake', 60, 'images/menu/ميلك شيك مكس بيري.webp', 1),
('p66', 'نوتيلا', 'Nutella Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك نوتيلا.webp', 1),
('p67', 'وايت نوتيلا براوني', 'White Nutella Brownie Milkshake', 'milkshake', 70, 'images/menu/ميلك شيك وايت نوتيلا براوني.png', 1),
('p68', 'باشون فروت', 'Passion Fruit Milkshake', 'milkshake', 65, 'images/menu/ميلك شيك باشون فروت.png', 1),
('p69', 'كلاسيك', 'Classic Yogurt', 'yogurt', 60, 'images/menu/زبادي كلاسيك.png', 1),
('p70', 'مانجو', 'Mango Yogurt', 'yogurt', 70, 'images/menu/زبادي مانجو.webp', 1),
('p71', 'فراوله', 'Strawberry Yogurt', 'yogurt', 70, 'images/menu/زبادي فراوله.png', 1),
('p72', 'خوخ', 'Peach Yogurt', 'yogurt', 70, 'images/menu/زبادي خوخ.webp', 1),
('p73', 'موز', 'Banana Yogurt', 'yogurt', 70, 'images/menu/موز.webp', 1),
('p74', 'بلو بيري', 'Blueberry Yogurt', 'yogurt', 70, 'images/menu/زبادي بلو بيري.webp', 1),
('p75', 'باشن فروت', 'Passion Fruit Yogurt', 'yogurt', 70, 'images/menu/زبادي باشن فروت.webp', 1),
('p76', 'عسل', 'Honey Yogurt', 'yogurt', 65, 'images/menu/زبادي عسل.png', 1),
('p77', 'مكس فواكه', 'Mixed Fruit Yogurt', 'yogurt', 80, 'images/menu/زبادي مكس فواكه.png', 1),
('p78', 'ليمون', 'Lemon Juice', 'juice', 50, 'images/menu/ليمون.webp', 1),
('p79', 'ليمون نعناع', 'Mint Lemon Juice', 'juice', 55, 'images/menu/ليمون نعناع.webp', 1),
('p80', 'برتقال', 'Orange Juice', 'juice', 60, 'images/menu/برتقال.webp', 1),
('p81', 'فراولة', 'Strawberry Juice', 'juice', 60, 'images/menu/فراولة.webp', 1),
('p82', 'مانجا', 'Mango Juice', 'juice', 70, 'images/menu/مانجا.webp', 1),
('p83', 'جوافه', 'Guava Juice', 'juice', 70, 'images/menu/جوافه.webp', 1),
('p84', 'موز', 'Banana Juice', 'juice', 70, 'images/menu/موز.webp', 1),
('p85', 'بطيخ', 'Watermelon Juice', 'juice', 60, 'images/menu/بطيخ.webp', 1),
('p86', 'بلح', 'Dates Juice', 'juice', 75, 'images/menu/بلح.png', 1),
('p87', 'افوكادو', 'Avocado Juice', 'juice', 80, 'images/menu/افوكادو.webp', 1),
('p88', 'ديلايت بانش', 'Delight Punch', 'cocktail', 65, 'images/menu/ديلايت بانش.png', 1),
('p89', 'تيمارا', 'Timara', 'cocktail', 65, 'images/menu/تيمارا.png', 1),
('p90', 'فلوريدا', 'Florida', 'cocktail', 65, 'images/menu/فلوريدا.webp', 1),
('p91', 'دابومبا', 'Dabumba', 'cocktail', 70, 'images/menu/دابومبا.png', 1),
('p92', 'وايت اوشن', 'White Ocean', 'cocktail', 70, 'images/menu/وايت اوشن.webp', 1),
('p93', 'شهر زاد', 'Shahrzad', 'cocktail', 70, 'images/menu/شهر زاد.png', 1),
('p94', 'لاروز', 'La Rose', 'cocktail', 75, 'images/menu/لاروز.png', 1),
('p95', 'صن رايز', 'Sunrise Mojito', 'mojito', 50, 'images/menu/موهيتو صن رايز.webp', 1),
('p96', 'صن شاين', 'Sunshine Mojito', 'mojito', 50, 'images/menu/موهيتو صن شاين.webp', 1),
('p97', 'باشن فروت', 'Passion Fruit Mojito', 'mojito', 50, 'images/menu/موهيتو باشن فروت.png', 1),
('p98', 'توت', 'Berry Mojito', 'mojito', 50, 'images/menu/موهيتو توت.webp', 1),
('p99', 'شيري كولا', 'Cherry Cola Mojito', 'mojito', 50, 'images/menu/موهيتو شيري كولا.png', 1),
('p100', 'شعير', 'Barley Mojito', 'mojito', 55, 'images/menu/موهيتو شعير.webp', 1),
('p101', 'باور صودا', 'Power Soda Mojito', 'mojito', 75, 'images/menu/باور صودا.png', 1),
('p102', 'بيبسي', 'Pepsi', 'cans', 30, 'images/menu/بيبسي.webp', 1),
('p103', 'بيبسي دايت', 'Diet Pepsi', 'cans', 30, 'images/menu/بيبسي دايت.webp', 1),
('p104', 'اسبرايت', 'Sprite', 'cans', 30, 'images/menu/اسبرايت.webp', 1),
('p105', 'ميرندا', 'Miranda', 'cans', 30, 'images/menu/ميرندا.webp', 1),
('p106', 'فانتا', 'Fanta', 'cans', 30, 'images/menu/فانتا.webp', 1),
('p107', 'سفن اب', '7UP', 'cans', 30, 'images/menu/سفن اب.webp', 1),
('p108', 'ماونتن ديو', 'Mountain Dew', 'cans', 30, 'images/menu/ماونتن ديو.webp', 1),
('p109', 'تويست', 'Twist', 'cans', 30, 'images/menu/تويست.webp', 1),
('p110', 'شويبس', 'Schweppes', 'cans', 30, 'images/menu/شويبس.webp', 1),
('p111', 'فيروز', 'Fayrouz', 'cans', 35, 'images/menu/فيروز.webp', 1),
('p112', 'في كولا', 'V Cola', 'cans', 35, 'images/menu/في كولا.webp', 1),
('p113', 'فيوري', 'Fuego', 'cans', 30, 'images/menu/فيوري.webp', 1),
('p114', 'بيريل', 'Birell', 'cans', 35, 'images/menu/بيريل.webp', 1),
('p115', 'ريد بول', 'Red Bull', 'cans', 75, 'images/menu/ريد بول.webp', 1),
('p116', 'مونستر', 'Monster', 'cans', 75, 'images/menu/مونستر.webp', 1),
('p117', 'وافل دارك', 'Dark Waffle', 'desserts', 65, 'images/menu/وافل دارك.png', 1),
('p118', 'وافل نوتيلا', 'Nutella Waffle', 'desserts', 70, 'images/menu/وافل نوتيلا.png', 1),
('p119', 'وافل وايت', 'White Waffle', 'desserts', 70, 'images/menu/وافل وايت.png', 1),
('p120', 'وافل لوتس', 'Lotus Waffle', 'desserts', 70, 'images/menu/وافل لوتس.png', 1),
('p121', 'وافل اوريو', 'Oreo Waffle', 'desserts', 75, 'images/menu/وافل اوريو.png', 1),
('p122', 'وافل ايس كريم & موز', 'Ice Cream & Banana Waffle', 'desserts', 80, 'images/menu/وافل ايس كريم & موز.png', 1),
('p123', 'مولتن كيك', 'Molten Cake', 'desserts', 65, 'images/menu/مولتن كيك.png', 1),
('p124', 'مولتن ايس كريم', 'Molten Ice Cream', 'desserts', 70, 'images/menu/مولتن ايس كريم.png', 1),
('p125', 'سينابون', 'Cinnabon', 'desserts', 55, 'images/menu/سينابون.png', 1),
('p126', 'سينابون نوتيلا', 'Nutella Cinnabon', 'desserts', 60, 'images/menu/سينابون نوتيلا.png', 1),
('p127', 'براونيز', 'Brownies', 'desserts', 50, 'images/menu/براونيز.png', 1),
('p128', 'فروت سالط', 'Fruit Salad', 'desserts', 60, 'images/menu/فروت سالط.png', 1),
('p129', 'فروت سالط ايس كريم', 'Fruit Salad with Ice Cream', 'desserts', 70, 'images/menu/فروت سالط ايس كريم.png', 1),
('p130', 'فروت سالط ايس كريم مكسرات', 'Fruit Salad with Ice Cream & Nuts', 'desserts', 75, 'images/menu/فروت سالط ايس كريم مكسرات.png', 1)
ON CONFLICT (id) DO NOTHING;
